

enum SpellSchool
{
	SPELL_SCHOOL_ARCANE		=	0x01,
	SPELL_SCHOOL_FIRE		=   0x02,
	SPELL_SCHOOL_FROST		=	0x03,
	SPELL_SCHOOL_NATURE		=	0x04,
	SPELL_SCHOOL_PHYSICAL	=	0x05,
	SPELL_SCHOOL_SHADOW		=	0x06,
	SPELL_SCHOOL_HOLY		=	0x07
};
enum SpellResistance
{
	SPELL_RESISTANCE_ARCANE			=	0x01,
	SPELL_RESISTANCE_FIRE			=	0x02,
	SPELL_RESISTANCE_FROST			=	0x03,
	SPELL_RESISTANCE_NATURE			=	0x04,
	SPELL_RESISTANCE_PHYSICAL		=	0x05,
	SPELL_RESISTANCE_SHADOW			=	0x06,
	SPELL_RESISTANCE_HOLY			=	0x07
};

enum SpellCostPowerType
{
	SPELL_COST_POWER_TYPE_MANA				= 0x01,
	SPELL_COST_POWER_TYPE_RAGE				= 0x02,
	SPELL_COST_POWER_TYPE_FOCUS				= 0x03,
	SPELL_COST_POWER_TYPE_ENERGY			= 0x04,
	SPELL_COST_POWER_TYPE_RUNIC_POWER		= 0x05
};

enum SpellCostType
{
	SPELL_COST_TYPE_ABSOLUTE,
	SPELL_COST_TYPE_PERCENTAGE,
	SPELL_COST_TYPE_RElATIVE
};